version: '3'
services:
  nginx_createrepo:
    image: marksugar/nginx_createrepo
    container_name: nginx_createrepo
    restart: always
    network_mode: "host"
    volumes:
      - /data/mirrors:/data
      - /etc/localtime:/etc/localtime:ro      
    environment:
      - NGINX_PORT=80
      - SERVER_NAME=localhost
